// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface AudioConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AudioConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.AudioConfig.AudioEncoding aue = 1;</code>
   */
  int getAueValue();
  /**
   * <code>.AudioConfig.AudioEncoding aue = 1;</code>
   */
  com.databaker.hyzx.speech.AudioConfig.AudioEncoding getAue();

  /**
   * <pre>
   * 采样率（范围为8000-48000）
   * </pre>
   *
   * <code>int32 sampleRate = 2;</code>
   */
  int getSampleRate();
}
