// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface SpeechConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpeechConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   */
  int getLangValue();
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   */
  com.databaker.hyzx.speech.SpeechConfig.Language getLang();

  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   */
  int getSceneValue();
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   */
  com.databaker.hyzx.speech.SpeechConfig.Scene getScene();

  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  java.util.List<String>
      getCustomWordList();
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  int getCustomWordCount();
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  String getCustomWord(int index);
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  com.google.protobuf.ByteString
      getCustomWordBytes(int index);

  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  java.util.List<Integer> getUseCustomWordsIdList();
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  int getUseCustomWordsIdCount();
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  int getUseCustomWordsId(int index);

  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   */
  int getRecognizeTypeValue();
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   */
  com.databaker.hyzx.speech.SpeechConfig.RecognizeType getRecognizeType();

  /**
   * <pre>
   * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
   * </pre>
   *
   * <code>bool disableConvertNumber = 6;</code>
   */
  boolean getDisableConvertNumber();

  /**
   * <pre>
   * 加标点。默认false，开启添加标点。true，关闭添加标点。
   * </pre>
   *
   * <code>bool disablePunctuation = 7;</code>
   */
  boolean getDisablePunctuation();

  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  boolean hasWordsReplace();
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  com.databaker.hyzx.speech.WordsReplace getWordsReplace();
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  com.databaker.hyzx.speech.WordsReplaceOrBuilder getWordsReplaceOrBuilder();

  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  java.util.List<String>
      getKeyWordsList();
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  int getKeyWordsCount();
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  String getKeyWords(int index);
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  com.google.protobuf.ByteString
      getKeyWordsBytes(int index);
}
