// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

/**
 * <pre>
 * 识别相关设置
 * </pre>
 *
 * Protobuf type {@code SpeechConfig}
 */
public  final class SpeechConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SpeechConfig)
    SpeechConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechConfig.newBuilder() to construct.
  private SpeechConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechConfig() {
    lang_ = 0;
    scene_ = 0;
    customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    useCustomWordsId_ = java.util.Collections.emptyList();
    recognizeType_ = 0;
    disableConvertNumber_ = false;
    disablePunctuation_ = false;
    keyWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeechConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            lang_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            scene_ = rawValue;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              customWord_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            customWord_.add(s);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              useCustomWordsId_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            useCustomWordsId_.add(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              useCustomWordsId_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              useCustomWordsId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            recognizeType_ = rawValue;
            break;
          }
          case 48: {

            disableConvertNumber_ = input.readBool();
            break;
          }
          case 56: {

            disablePunctuation_ = input.readBool();
            break;
          }
          case 66: {
            com.databaker.hyzx.speech.WordsReplace.Builder subBuilder = null;
            if (wordsReplace_ != null) {
              subBuilder = wordsReplace_.toBuilder();
            }
            wordsReplace_ = input.readMessage(com.databaker.hyzx.speech.WordsReplace.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(wordsReplace_);
              wordsReplace_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              keyWords_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            keyWords_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        customWord_ = customWord_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        useCustomWordsId_ = java.util.Collections.unmodifiableList(useCustomWordsId_);
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        keyWords_ = keyWords_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_SpeechConfig_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_SpeechConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.databaker.hyzx.speech.SpeechConfig.class, com.databaker.hyzx.speech.SpeechConfig.Builder.class);
  }

  /**
   * <pre>
   * 转写的语言
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.Language}
   */
  public enum Language
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <code>MANDARIN = 1;</code>
     */
    MANDARIN(1),
    /**
     * <code>ENGLISH = 2;</code>
     */
    ENGLISH(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <code>MANDARIN = 1;</code>
     */
    public static final int MANDARIN_VALUE = 1;
    /**
     * <code>ENGLISH = 2;</code>
     */
    public static final int ENGLISH_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Language valueOf(int value) {
      return forNumber(value);
    }

    public static Language forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return MANDARIN;
        case 2: return ENGLISH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Language>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Language> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Language>() {
            public Language findValueByNumber(int number) {
              return Language.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.SpeechConfig.getDescriptor().getEnumTypes().get(0);
    }

    private static final Language[] VALUES = values();

    public static Language valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Language(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.Language)
  }

  /**
   * <pre>
   * 情景模式，目前仅支持通用0
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.Scene}
   */
  public enum Scene
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GENERALSCENE = 0;</code>
     */
    GENERALSCENE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GENERALSCENE = 0;</code>
     */
    public static final int GENERALSCENE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Scene valueOf(int value) {
      return forNumber(value);
    }

    public static Scene forNumber(int value) {
      switch (value) {
        case 0: return GENERALSCENE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Scene>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Scene> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Scene>() {
            public Scene findValueByNumber(int number) {
              return Scene.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.SpeechConfig.getDescriptor().getEnumTypes().get(1);
    }

    private static final Scene[] VALUES = values();

    public static Scene valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Scene(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.Scene)
  }

  /**
   * <pre>
   * 识别类型（0-全部，1-仅逐句, 2-仅逐字）
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.RecognizeType}
   */
  public enum RecognizeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL = 0;</code>
     */
    ALL(0),
    /**
     * <code>UTTERANCE = 1;</code>
     */
    UTTERANCE(1),
    /**
     * <code>STREAMING = 2;</code>
     */
    STREAMING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ALL = 0;</code>
     */
    public static final int ALL_VALUE = 0;
    /**
     * <code>UTTERANCE = 1;</code>
     */
    public static final int UTTERANCE_VALUE = 1;
    /**
     * <code>STREAMING = 2;</code>
     */
    public static final int STREAMING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RecognizeType valueOf(int value) {
      return forNumber(value);
    }

    public static RecognizeType forNumber(int value) {
      switch (value) {
        case 0: return ALL;
        case 1: return UTTERANCE;
        case 2: return STREAMING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RecognizeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RecognizeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RecognizeType>() {
            public RecognizeType findValueByNumber(int number) {
              return RecognizeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.SpeechConfig.getDescriptor().getEnumTypes().get(2);
    }

    private static final RecognizeType[] VALUES = values();

    public static RecognizeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RecognizeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.RecognizeType)
  }

  private int bitField0_;
  public static final int LANG_FIELD_NUMBER = 1;
  private int lang_;
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   */
  public int getLangValue() {
    return lang_;
  }
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   */
  public com.databaker.hyzx.speech.SpeechConfig.Language getLang() {
    com.databaker.hyzx.speech.SpeechConfig.Language result = com.databaker.hyzx.speech.SpeechConfig.Language.valueOf(lang_);
    return result == null ? com.databaker.hyzx.speech.SpeechConfig.Language.UNRECOGNIZED : result;
  }

  public static final int SCENE_FIELD_NUMBER = 2;
  private int scene_;
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   */
  public int getSceneValue() {
    return scene_;
  }
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   */
  public com.databaker.hyzx.speech.SpeechConfig.Scene getScene() {
    com.databaker.hyzx.speech.SpeechConfig.Scene result = com.databaker.hyzx.speech.SpeechConfig.Scene.valueOf(scene_);
    return result == null ? com.databaker.hyzx.speech.SpeechConfig.Scene.UNRECOGNIZED : result;
  }

  public static final int CUSTOMWORD_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList customWord_;
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCustomWordList() {
    return customWord_;
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  public int getCustomWordCount() {
    return customWord_.size();
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  public String getCustomWord(int index) {
    return customWord_.get(index);
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCustomWordBytes(int index) {
    return customWord_.getByteString(index);
  }

  public static final int USECUSTOMWORDSID_FIELD_NUMBER = 4;
  private java.util.List<Integer> useCustomWordsId_;
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  public java.util.List<Integer>
      getUseCustomWordsIdList() {
    return useCustomWordsId_;
  }
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  public int getUseCustomWordsIdCount() {
    return useCustomWordsId_.size();
  }
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   */
  public int getUseCustomWordsId(int index) {
    return useCustomWordsId_.get(index);
  }
  private int useCustomWordsIdMemoizedSerializedSize = -1;

  public static final int RECOGNIZETYPE_FIELD_NUMBER = 5;
  private int recognizeType_;
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   */
  public int getRecognizeTypeValue() {
    return recognizeType_;
  }
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   */
  public com.databaker.hyzx.speech.SpeechConfig.RecognizeType getRecognizeType() {
    com.databaker.hyzx.speech.SpeechConfig.RecognizeType result = com.databaker.hyzx.speech.SpeechConfig.RecognizeType.valueOf(recognizeType_);
    return result == null ? com.databaker.hyzx.speech.SpeechConfig.RecognizeType.UNRECOGNIZED : result;
  }

  public static final int DISABLECONVERTNUMBER_FIELD_NUMBER = 6;
  private boolean disableConvertNumber_;
  /**
   * <pre>
   * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
   * </pre>
   *
   * <code>bool disableConvertNumber = 6;</code>
   */
  public boolean getDisableConvertNumber() {
    return disableConvertNumber_;
  }

  public static final int DISABLEPUNCTUATION_FIELD_NUMBER = 7;
  private boolean disablePunctuation_;
  /**
   * <pre>
   * 加标点。默认false，开启添加标点。true，关闭添加标点。
   * </pre>
   *
   * <code>bool disablePunctuation = 7;</code>
   */
  public boolean getDisablePunctuation() {
    return disablePunctuation_;
  }

  public static final int WORDSREPLACE_FIELD_NUMBER = 8;
  private com.databaker.hyzx.speech.WordsReplace wordsReplace_;
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  public boolean hasWordsReplace() {
    return wordsReplace_ != null;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  public com.databaker.hyzx.speech.WordsReplace getWordsReplace() {
    return wordsReplace_ == null ? com.databaker.hyzx.speech.WordsReplace.getDefaultInstance() : wordsReplace_;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  public com.databaker.hyzx.speech.WordsReplaceOrBuilder getWordsReplaceOrBuilder() {
    return getWordsReplace();
  }

  public static final int KEYWORDS_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList keyWords_;
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getKeyWordsList() {
    return keyWords_;
  }
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  public int getKeyWordsCount() {
    return keyWords_.size();
  }
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  public String getKeyWords(int index) {
    return keyWords_.get(index);
  }
  /**
   * <pre>
   * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
   * </pre>
   *
   * <code>repeated string keyWords = 9;</code>
   */
  public com.google.protobuf.ByteString
      getKeyWordsBytes(int index) {
    return keyWords_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (lang_ != com.databaker.hyzx.speech.SpeechConfig.Language.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, lang_);
    }
    if (scene_ != com.databaker.hyzx.speech.SpeechConfig.Scene.GENERALSCENE.getNumber()) {
      output.writeEnum(2, scene_);
    }
    for (int i = 0; i < customWord_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customWord_.getRaw(i));
    }
    if (getUseCustomWordsIdList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(useCustomWordsIdMemoizedSerializedSize);
    }
    for (int i = 0; i < useCustomWordsId_.size(); i++) {
      output.writeInt32NoTag(useCustomWordsId_.get(i));
    }
    if (recognizeType_ != com.databaker.hyzx.speech.SpeechConfig.RecognizeType.ALL.getNumber()) {
      output.writeEnum(5, recognizeType_);
    }
    if (disableConvertNumber_ != false) {
      output.writeBool(6, disableConvertNumber_);
    }
    if (disablePunctuation_ != false) {
      output.writeBool(7, disablePunctuation_);
    }
    if (wordsReplace_ != null) {
      output.writeMessage(8, getWordsReplace());
    }
    for (int i = 0; i < keyWords_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, keyWords_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lang_ != com.databaker.hyzx.speech.SpeechConfig.Language.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, lang_);
    }
    if (scene_ != com.databaker.hyzx.speech.SpeechConfig.Scene.GENERALSCENE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, scene_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < customWord_.size(); i++) {
        dataSize += computeStringSizeNoTag(customWord_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCustomWordList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < useCustomWordsId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(useCustomWordsId_.get(i));
      }
      size += dataSize;
      if (!getUseCustomWordsIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      useCustomWordsIdMemoizedSerializedSize = dataSize;
    }
    if (recognizeType_ != com.databaker.hyzx.speech.SpeechConfig.RecognizeType.ALL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, recognizeType_);
    }
    if (disableConvertNumber_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, disableConvertNumber_);
    }
    if (disablePunctuation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, disablePunctuation_);
    }
    if (wordsReplace_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getWordsReplace());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < keyWords_.size(); i++) {
        dataSize += computeStringSizeNoTag(keyWords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeyWordsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.databaker.hyzx.speech.SpeechConfig)) {
      return super.equals(obj);
    }
    com.databaker.hyzx.speech.SpeechConfig other = (com.databaker.hyzx.speech.SpeechConfig) obj;

    boolean result = true;
    result = result && lang_ == other.lang_;
    result = result && scene_ == other.scene_;
    result = result && getCustomWordList()
        .equals(other.getCustomWordList());
    result = result && getUseCustomWordsIdList()
        .equals(other.getUseCustomWordsIdList());
    result = result && recognizeType_ == other.recognizeType_;
    result = result && (getDisableConvertNumber()
        == other.getDisableConvertNumber());
    result = result && (getDisablePunctuation()
        == other.getDisablePunctuation());
    result = result && (hasWordsReplace() == other.hasWordsReplace());
    if (hasWordsReplace()) {
      result = result && getWordsReplace()
          .equals(other.getWordsReplace());
    }
    result = result && getKeyWordsList()
        .equals(other.getKeyWordsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + lang_;
    hash = (37 * hash) + SCENE_FIELD_NUMBER;
    hash = (53 * hash) + scene_;
    if (getCustomWordCount() > 0) {
      hash = (37 * hash) + CUSTOMWORD_FIELD_NUMBER;
      hash = (53 * hash) + getCustomWordList().hashCode();
    }
    if (getUseCustomWordsIdCount() > 0) {
      hash = (37 * hash) + USECUSTOMWORDSID_FIELD_NUMBER;
      hash = (53 * hash) + getUseCustomWordsIdList().hashCode();
    }
    hash = (37 * hash) + RECOGNIZETYPE_FIELD_NUMBER;
    hash = (53 * hash) + recognizeType_;
    hash = (37 * hash) + DISABLECONVERTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableConvertNumber());
    hash = (37 * hash) + DISABLEPUNCTUATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisablePunctuation());
    if (hasWordsReplace()) {
      hash = (37 * hash) + WORDSREPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getWordsReplace().hashCode();
    }
    if (getKeyWordsCount() > 0) {
      hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getKeyWordsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.SpeechConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.databaker.hyzx.speech.SpeechConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 识别相关设置
   * </pre>
   *
   * Protobuf type {@code SpeechConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SpeechConfig)
      com.databaker.hyzx.speech.SpeechConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_SpeechConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_SpeechConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.databaker.hyzx.speech.SpeechConfig.class, com.databaker.hyzx.speech.SpeechConfig.Builder.class);
    }

    // Construct using com.databaker.hyzx.speech.SpeechConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      lang_ = 0;

      scene_ = 0;

      customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      useCustomWordsId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      recognizeType_ = 0;

      disableConvertNumber_ = false;

      disablePunctuation_ = false;

      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = null;
      } else {
        wordsReplace_ = null;
        wordsReplaceBuilder_ = null;
      }
      keyWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_SpeechConfig_descriptor;
    }

    public com.databaker.hyzx.speech.SpeechConfig getDefaultInstanceForType() {
      return com.databaker.hyzx.speech.SpeechConfig.getDefaultInstance();
    }

    public com.databaker.hyzx.speech.SpeechConfig build() {
      com.databaker.hyzx.speech.SpeechConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.databaker.hyzx.speech.SpeechConfig buildPartial() {
      com.databaker.hyzx.speech.SpeechConfig result = new com.databaker.hyzx.speech.SpeechConfig(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.lang_ = lang_;
      result.scene_ = scene_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        customWord_ = customWord_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.customWord_ = customWord_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        useCustomWordsId_ = java.util.Collections.unmodifiableList(useCustomWordsId_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.useCustomWordsId_ = useCustomWordsId_;
      result.recognizeType_ = recognizeType_;
      result.disableConvertNumber_ = disableConvertNumber_;
      result.disablePunctuation_ = disablePunctuation_;
      if (wordsReplaceBuilder_ == null) {
        result.wordsReplace_ = wordsReplace_;
      } else {
        result.wordsReplace_ = wordsReplaceBuilder_.build();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        keyWords_ = keyWords_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.keyWords_ = keyWords_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.databaker.hyzx.speech.SpeechConfig) {
        return mergeFrom((com.databaker.hyzx.speech.SpeechConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.databaker.hyzx.speech.SpeechConfig other) {
      if (other == com.databaker.hyzx.speech.SpeechConfig.getDefaultInstance()) return this;
      if (other.lang_ != 0) {
        setLangValue(other.getLangValue());
      }
      if (other.scene_ != 0) {
        setSceneValue(other.getSceneValue());
      }
      if (!other.customWord_.isEmpty()) {
        if (customWord_.isEmpty()) {
          customWord_ = other.customWord_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureCustomWordIsMutable();
          customWord_.addAll(other.customWord_);
        }
        onChanged();
      }
      if (!other.useCustomWordsId_.isEmpty()) {
        if (useCustomWordsId_.isEmpty()) {
          useCustomWordsId_ = other.useCustomWordsId_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureUseCustomWordsIdIsMutable();
          useCustomWordsId_.addAll(other.useCustomWordsId_);
        }
        onChanged();
      }
      if (other.recognizeType_ != 0) {
        setRecognizeTypeValue(other.getRecognizeTypeValue());
      }
      if (other.getDisableConvertNumber() != false) {
        setDisableConvertNumber(other.getDisableConvertNumber());
      }
      if (other.getDisablePunctuation() != false) {
        setDisablePunctuation(other.getDisablePunctuation());
      }
      if (other.hasWordsReplace()) {
        mergeWordsReplace(other.getWordsReplace());
      }
      if (!other.keyWords_.isEmpty()) {
        if (keyWords_.isEmpty()) {
          keyWords_ = other.keyWords_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureKeyWordsIsMutable();
          keyWords_.addAll(other.keyWords_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.databaker.hyzx.speech.SpeechConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.databaker.hyzx.speech.SpeechConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int lang_ = 0;
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     */
    public int getLangValue() {
      return lang_;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     */
    public Builder setLangValue(int value) {
      lang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     */
    public com.databaker.hyzx.speech.SpeechConfig.Language getLang() {
      com.databaker.hyzx.speech.SpeechConfig.Language result = com.databaker.hyzx.speech.SpeechConfig.Language.valueOf(lang_);
      return result == null ? com.databaker.hyzx.speech.SpeechConfig.Language.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     */
    public Builder setLang(com.databaker.hyzx.speech.SpeechConfig.Language value) {
      if (value == null) {
        throw new NullPointerException();
      }

      lang_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     */
    public Builder clearLang() {

      lang_ = 0;
      onChanged();
      return this;
    }

    private int scene_ = 0;
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     */
    public int getSceneValue() {
      return scene_;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     */
    public Builder setSceneValue(int value) {
      scene_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     */
    public com.databaker.hyzx.speech.SpeechConfig.Scene getScene() {
      com.databaker.hyzx.speech.SpeechConfig.Scene result = com.databaker.hyzx.speech.SpeechConfig.Scene.valueOf(scene_);
      return result == null ? com.databaker.hyzx.speech.SpeechConfig.Scene.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     */
    public Builder setScene(com.databaker.hyzx.speech.SpeechConfig.Scene value) {
      if (value == null) {
        throw new NullPointerException();
      }

      scene_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     */
    public Builder clearScene() {

      scene_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCustomWordIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        customWord_ = new com.google.protobuf.LazyStringArrayList(customWord_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCustomWordList() {
      return customWord_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public int getCustomWordCount() {
      return customWord_.size();
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public String getCustomWord(int index) {
      return customWord_.get(index);
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCustomWordBytes(int index) {
      return customWord_.getByteString(index);
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public Builder setCustomWord(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomWordIsMutable();
      customWord_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public Builder addCustomWord(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomWordIsMutable();
      customWord_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public Builder addAllCustomWord(
        Iterable<String> values) {
      ensureCustomWordIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, customWord_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public Builder clearCustomWord() {
      customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     */
    public Builder addCustomWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCustomWordIsMutable();
      customWord_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Integer> useCustomWordsId_ = java.util.Collections.emptyList();
    private void ensureUseCustomWordsIdIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        useCustomWordsId_ = new java.util.ArrayList<Integer>(useCustomWordsId_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public java.util.List<Integer>
        getUseCustomWordsIdList() {
      return java.util.Collections.unmodifiableList(useCustomWordsId_);
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public int getUseCustomWordsIdCount() {
      return useCustomWordsId_.size();
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public int getUseCustomWordsId(int index) {
      return useCustomWordsId_.get(index);
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public Builder setUseCustomWordsId(
        int index, int value) {
      ensureUseCustomWordsIdIsMutable();
      useCustomWordsId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public Builder addUseCustomWordsId(int value) {
      ensureUseCustomWordsIdIsMutable();
      useCustomWordsId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public Builder addAllUseCustomWordsId(
        Iterable<? extends Integer> values) {
      ensureUseCustomWordsIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, useCustomWordsId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     */
    public Builder clearUseCustomWordsId() {
      useCustomWordsId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private int recognizeType_ = 0;
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     */
    public int getRecognizeTypeValue() {
      return recognizeType_;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     */
    public Builder setRecognizeTypeValue(int value) {
      recognizeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     */
    public com.databaker.hyzx.speech.SpeechConfig.RecognizeType getRecognizeType() {
      com.databaker.hyzx.speech.SpeechConfig.RecognizeType result = com.databaker.hyzx.speech.SpeechConfig.RecognizeType.valueOf(recognizeType_);
      return result == null ? com.databaker.hyzx.speech.SpeechConfig.RecognizeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     */
    public Builder setRecognizeType(com.databaker.hyzx.speech.SpeechConfig.RecognizeType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      recognizeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     */
    public Builder clearRecognizeType() {

      recognizeType_ = 0;
      onChanged();
      return this;
    }

    private boolean disableConvertNumber_ ;
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     */
    public boolean getDisableConvertNumber() {
      return disableConvertNumber_;
    }
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     */
    public Builder setDisableConvertNumber(boolean value) {

      disableConvertNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     */
    public Builder clearDisableConvertNumber() {

      disableConvertNumber_ = false;
      onChanged();
      return this;
    }

    private boolean disablePunctuation_ ;
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     */
    public boolean getDisablePunctuation() {
      return disablePunctuation_;
    }
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     */
    public Builder setDisablePunctuation(boolean value) {

      disablePunctuation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     */
    public Builder clearDisablePunctuation() {

      disablePunctuation_ = false;
      onChanged();
      return this;
    }

    private com.databaker.hyzx.speech.WordsReplace wordsReplace_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.WordsReplace, com.databaker.hyzx.speech.WordsReplace.Builder, com.databaker.hyzx.speech.WordsReplaceOrBuilder> wordsReplaceBuilder_;
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public boolean hasWordsReplace() {
      return wordsReplaceBuilder_ != null || wordsReplace_ != null;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public com.databaker.hyzx.speech.WordsReplace getWordsReplace() {
      if (wordsReplaceBuilder_ == null) {
        return wordsReplace_ == null ? com.databaker.hyzx.speech.WordsReplace.getDefaultInstance() : wordsReplace_;
      } else {
        return wordsReplaceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder setWordsReplace(com.databaker.hyzx.speech.WordsReplace value) {
      if (wordsReplaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wordsReplace_ = value;
        onChanged();
      } else {
        wordsReplaceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder setWordsReplace(
        com.databaker.hyzx.speech.WordsReplace.Builder builderForValue) {
      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = builderForValue.build();
        onChanged();
      } else {
        wordsReplaceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder mergeWordsReplace(com.databaker.hyzx.speech.WordsReplace value) {
      if (wordsReplaceBuilder_ == null) {
        if (wordsReplace_ != null) {
          wordsReplace_ =
            com.databaker.hyzx.speech.WordsReplace.newBuilder(wordsReplace_).mergeFrom(value).buildPartial();
        } else {
          wordsReplace_ = value;
        }
        onChanged();
      } else {
        wordsReplaceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder clearWordsReplace() {
      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = null;
        onChanged();
      } else {
        wordsReplace_ = null;
        wordsReplaceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public com.databaker.hyzx.speech.WordsReplace.Builder getWordsReplaceBuilder() {

      onChanged();
      return getWordsReplaceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public com.databaker.hyzx.speech.WordsReplaceOrBuilder getWordsReplaceOrBuilder() {
      if (wordsReplaceBuilder_ != null) {
        return wordsReplaceBuilder_.getMessageOrBuilder();
      } else {
        return wordsReplace_ == null ?
            com.databaker.hyzx.speech.WordsReplace.getDefaultInstance() : wordsReplace_;
      }
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.WordsReplace, com.databaker.hyzx.speech.WordsReplace.Builder, com.databaker.hyzx.speech.WordsReplaceOrBuilder>
        getWordsReplaceFieldBuilder() {
      if (wordsReplaceBuilder_ == null) {
        wordsReplaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.databaker.hyzx.speech.WordsReplace, com.databaker.hyzx.speech.WordsReplace.Builder, com.databaker.hyzx.speech.WordsReplaceOrBuilder>(
                getWordsReplace(),
                getParentForChildren(),
                isClean());
        wordsReplace_ = null;
      }
      return wordsReplaceBuilder_;
    }

    private com.google.protobuf.LazyStringList keyWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKeyWordsIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        keyWords_ = new com.google.protobuf.LazyStringArrayList(keyWords_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeyWordsList() {
      return keyWords_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public int getKeyWordsCount() {
      return keyWords_.size();
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public String getKeyWords(int index) {
      return keyWords_.get(index);
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public com.google.protobuf.ByteString
        getKeyWordsBytes(int index) {
      return keyWords_.getByteString(index);
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public Builder setKeyWords(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyWordsIsMutable();
      keyWords_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public Builder addKeyWords(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyWordsIsMutable();
      keyWords_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public Builder addAllKeyWords(
        Iterable<String> values) {
      ensureKeyWordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keyWords_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public Builder clearKeyWords() {
      keyWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关键词识别。转写结果中返回同音词。（支持词库总数不超过30个。支持中文2-4个字）*
     * </pre>
     *
     * <code>repeated string keyWords = 9;</code>
     */
    public Builder addKeyWordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKeyWordsIsMutable();
      keyWords_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SpeechConfig)
  }

  // @@protoc_insertion_point(class_scope:SpeechConfig)
  private static final com.databaker.hyzx.speech.SpeechConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.databaker.hyzx.speech.SpeechConfig();
  }

  public static com.databaker.hyzx.speech.SpeechConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechConfig>
      PARSER = new com.google.protobuf.AbstractParser<SpeechConfig>() {
    public SpeechConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeechConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeechConfig> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpeechConfig> getParserForType() {
    return PARSER;
  }

  public com.databaker.hyzx.speech.SpeechConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

