// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface StreamingSpeechResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   */
  String getGlobalStreamId();
  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   */
  com.google.protobuf.ByteString
      getGlobalStreamIdBytes();

  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  boolean hasResult();
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechResult getResult();
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder getResultOrBuilder();

  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  boolean hasStatus();
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechStatus getStatus();
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder getStatusOrBuilder();
}
