// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

/**
 * <pre>
 * 音频当前识别状态
 * </pre>
 *
 * Protobuf type {@code StreamingSpeechStatus}
 */
public  final class StreamingSpeechStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamingSpeechStatus)
    StreamingSpeechStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingSpeechStatus.newBuilder() to construct.
  private StreamingSpeechStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingSpeechStatus() {
    processedTimestamp_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamingSpeechStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            processedTimestamp_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechStatus_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.databaker.hyzx.speech.StreamingSpeechStatus.class, com.databaker.hyzx.speech.StreamingSpeechStatus.Builder.class);
  }

  public static final int PROCESSEDTIMESTAMP_FIELD_NUMBER = 1;
  private long processedTimestamp_;
  /**
   * <pre>
   * 当前音频处理进行到的时间点（音频开始时间为0）
   * </pre>
   *
   * <code>int64 processedTimestamp = 1;</code>
   */
  public long getProcessedTimestamp() {
    return processedTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (processedTimestamp_ != 0L) {
      output.writeInt64(1, processedTimestamp_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (processedTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, processedTimestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.databaker.hyzx.speech.StreamingSpeechStatus)) {
      return super.equals(obj);
    }
    com.databaker.hyzx.speech.StreamingSpeechStatus other = (com.databaker.hyzx.speech.StreamingSpeechStatus) obj;

    boolean result = true;
    result = result && (getProcessedTimestamp()
        == other.getProcessedTimestamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROCESSEDTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProcessedTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.databaker.hyzx.speech.StreamingSpeechStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 音频当前识别状态
   * </pre>
   *
   * Protobuf type {@code StreamingSpeechStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamingSpeechStatus)
      com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.databaker.hyzx.speech.StreamingSpeechStatus.class, com.databaker.hyzx.speech.StreamingSpeechStatus.Builder.class);
    }

    // Construct using com.databaker.hyzx.speech.StreamingSpeechStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      processedTimestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechStatus_descriptor;
    }

    public com.databaker.hyzx.speech.StreamingSpeechStatus getDefaultInstanceForType() {
      return com.databaker.hyzx.speech.StreamingSpeechStatus.getDefaultInstance();
    }

    public com.databaker.hyzx.speech.StreamingSpeechStatus build() {
      com.databaker.hyzx.speech.StreamingSpeechStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.databaker.hyzx.speech.StreamingSpeechStatus buildPartial() {
      com.databaker.hyzx.speech.StreamingSpeechStatus result = new com.databaker.hyzx.speech.StreamingSpeechStatus(this);
      result.processedTimestamp_ = processedTimestamp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.databaker.hyzx.speech.StreamingSpeechStatus) {
        return mergeFrom((com.databaker.hyzx.speech.StreamingSpeechStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.databaker.hyzx.speech.StreamingSpeechStatus other) {
      if (other == com.databaker.hyzx.speech.StreamingSpeechStatus.getDefaultInstance()) return this;
      if (other.getProcessedTimestamp() != 0L) {
        setProcessedTimestamp(other.getProcessedTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.databaker.hyzx.speech.StreamingSpeechStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.databaker.hyzx.speech.StreamingSpeechStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long processedTimestamp_ ;
    /**
     * <pre>
     * 当前音频处理进行到的时间点（音频开始时间为0）
     * </pre>
     *
     * <code>int64 processedTimestamp = 1;</code>
     */
    public long getProcessedTimestamp() {
      return processedTimestamp_;
    }
    /**
     * <pre>
     * 当前音频处理进行到的时间点（音频开始时间为0）
     * </pre>
     *
     * <code>int64 processedTimestamp = 1;</code>
     */
    public Builder setProcessedTimestamp(long value) {

      processedTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前音频处理进行到的时间点（音频开始时间为0）
     * </pre>
     *
     * <code>int64 processedTimestamp = 1;</code>
     */
    public Builder clearProcessedTimestamp() {

      processedTimestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamingSpeechStatus)
  }

  // @@protoc_insertion_point(class_scope:StreamingSpeechStatus)
  private static final com.databaker.hyzx.speech.StreamingSpeechStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.databaker.hyzx.speech.StreamingSpeechStatus();
  }

  public static com.databaker.hyzx.speech.StreamingSpeechStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingSpeechStatus>
      PARSER = new com.google.protobuf.AbstractParser<StreamingSpeechStatus>() {
    public StreamingSpeechStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamingSpeechStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamingSpeechStatus> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamingSpeechStatus> getParserForType() {
    return PARSER;
  }

  public com.databaker.hyzx.speech.StreamingSpeechStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

