// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface StreamingSpeechConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   */
  boolean hasAudioConfig();
  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   */
  com.databaker.hyzx.speech.AudioConfig getAudioConfig();
  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   */
  com.databaker.hyzx.speech.AudioConfigOrBuilder getAudioConfigOrBuilder();

  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   */
  boolean hasSpeechConfig();
  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   */
  com.databaker.hyzx.speech.SpeechConfig getSpeechConfig();
  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   */
  com.databaker.hyzx.speech.SpeechConfigOrBuilder getSpeechConfigOrBuilder();
}
