// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

/**
 * <pre>
 * 转写
 * </pre>
 *
 * Protobuf type {@code StreamingTranscription}
 */
public  final class StreamingTranscription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamingTranscription)
    StreamingTranscriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingTranscription.newBuilder() to construct.
  private StreamingTranscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingTranscription() {
    transcribedText_ = "";
    keyWordsType_ = java.util.Collections.emptyList();
    piece_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamingTranscription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            transcribedText_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              keyWordsType_ = new java.util.ArrayList<com.databaker.hyzx.speech.KeyWordsType>();
              mutable_bitField0_ |= 0x00000002;
            }
            keyWordsType_.add(
                input.readMessage(com.databaker.hyzx.speech.KeyWordsType.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              piece_ = new java.util.ArrayList<com.databaker.hyzx.speech.StreamingTranscriptionPiece>();
              mutable_bitField0_ |= 0x00000004;
            }
            piece_.add(
                input.readMessage(com.databaker.hyzx.speech.StreamingTranscriptionPiece.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        keyWordsType_ = java.util.Collections.unmodifiableList(keyWordsType_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        piece_ = java.util.Collections.unmodifiableList(piece_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingTranscription_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingTranscription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.databaker.hyzx.speech.StreamingTranscription.class, com.databaker.hyzx.speech.StreamingTranscription.Builder.class);
  }

  private int bitField0_;
  public static final int TRANSCRIBEDTEXT_FIELD_NUMBER = 1;
  private volatile Object transcribedText_;
  /**
   * <pre>
   * 转写结果
   * </pre>
   *
   * <code>string transcribedText = 1;</code>
   */
  public String getTranscribedText() {
    Object ref = transcribedText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transcribedText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 转写结果
   * </pre>
   *
   * <code>string transcribedText = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTranscribedTextBytes() {
    Object ref = transcribedText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      transcribedText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORDSTYPE_FIELD_NUMBER = 2;
  private java.util.List<com.databaker.hyzx.speech.KeyWordsType> keyWordsType_;
  /**
   * <pre>
   * 转写结果中包含热词的内容
   * </pre>
   *
   * <code>repeated .KeyWordsType keyWordsType = 2;</code>
   */
  public java.util.List<com.databaker.hyzx.speech.KeyWordsType> getKeyWordsTypeList() {
    return keyWordsType_;
  }
  /**
   * <pre>
   * 转写结果中包含热词的内容
   * </pre>
   *
   * <code>repeated .KeyWordsType keyWordsType = 2;</code>
   */
  public java.util.List<? extends com.databaker.hyzx.speech.KeyWordsTypeOrBuilder>
      getKeyWordsTypeOrBuilderList() {
    return keyWordsType_;
  }
  /**
   * <pre>
   * 转写结果中包含热词的内容
   * </pre>
   *
   * <code>repeated .KeyWordsType keyWordsType = 2;</code>
   */
  public int getKeyWordsTypeCount() {
    return keyWordsType_.size();
  }
  /**
   * <pre>
   * 转写结果中包含热词的内容
   * </pre>
   *
   * <code>repeated .KeyWordsType keyWordsType = 2;</code>
   */
  public com.databaker.hyzx.speech.KeyWordsType getKeyWordsType(int index) {
    return keyWordsType_.get(index);
  }
  /**
   * <pre>
   * 转写结果中包含热词的内容
   * </pre>
   *
   * <code>repeated .KeyWordsType keyWordsType = 2;</code>
   */
  public com.databaker.hyzx.speech.KeyWordsTypeOrBuilder getKeyWordsTypeOrBuilder(
      int index) {
    return keyWordsType_.get(index);
  }

  public static final int PIECE_FIELD_NUMBER = 3;
  private java.util.List<com.databaker.hyzx.speech.StreamingTranscriptionPiece> piece_;
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
   */
  public java.util.List<com.databaker.hyzx.speech.StreamingTranscriptionPiece> getPieceList() {
    return piece_;
  }
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
   */
  public java.util.List<? extends com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder>
      getPieceOrBuilderList() {
    return piece_;
  }
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
   */
  public int getPieceCount() {
    return piece_.size();
  }
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
   */
  public com.databaker.hyzx.speech.StreamingTranscriptionPiece getPiece(int index) {
    return piece_.get(index);
  }
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
   */
  public com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder getPieceOrBuilder(
      int index) {
    return piece_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTranscribedTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transcribedText_);
    }
    for (int i = 0; i < keyWordsType_.size(); i++) {
      output.writeMessage(2, keyWordsType_.get(i));
    }
    for (int i = 0; i < piece_.size(); i++) {
      output.writeMessage(3, piece_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTranscribedTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transcribedText_);
    }
    for (int i = 0; i < keyWordsType_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, keyWordsType_.get(i));
    }
    for (int i = 0; i < piece_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, piece_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.databaker.hyzx.speech.StreamingTranscription)) {
      return super.equals(obj);
    }
    com.databaker.hyzx.speech.StreamingTranscription other = (com.databaker.hyzx.speech.StreamingTranscription) obj;

    boolean result = true;
    result = result && getTranscribedText()
        .equals(other.getTranscribedText());
    result = result && getKeyWordsTypeList()
        .equals(other.getKeyWordsTypeList());
    result = result && getPieceList()
        .equals(other.getPieceList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSCRIBEDTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getTranscribedText().hashCode();
    if (getKeyWordsTypeCount() > 0) {
      hash = (37 * hash) + KEYWORDSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getKeyWordsTypeList().hashCode();
    }
    if (getPieceCount() > 0) {
      hash = (37 * hash) + PIECE_FIELD_NUMBER;
      hash = (53 * hash) + getPieceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingTranscription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.databaker.hyzx.speech.StreamingTranscription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 转写
   * </pre>
   *
   * Protobuf type {@code StreamingTranscription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamingTranscription)
      com.databaker.hyzx.speech.StreamingTranscriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingTranscription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingTranscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.databaker.hyzx.speech.StreamingTranscription.class, com.databaker.hyzx.speech.StreamingTranscription.Builder.class);
    }

    // Construct using com.databaker.hyzx.speech.StreamingTranscription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getKeyWordsTypeFieldBuilder();
        getPieceFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      transcribedText_ = "";

      if (keyWordsTypeBuilder_ == null) {
        keyWordsType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        keyWordsTypeBuilder_.clear();
      }
      if (pieceBuilder_ == null) {
        piece_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        pieceBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingTranscription_descriptor;
    }

    public com.databaker.hyzx.speech.StreamingTranscription getDefaultInstanceForType() {
      return com.databaker.hyzx.speech.StreamingTranscription.getDefaultInstance();
    }

    public com.databaker.hyzx.speech.StreamingTranscription build() {
      com.databaker.hyzx.speech.StreamingTranscription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.databaker.hyzx.speech.StreamingTranscription buildPartial() {
      com.databaker.hyzx.speech.StreamingTranscription result = new com.databaker.hyzx.speech.StreamingTranscription(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.transcribedText_ = transcribedText_;
      if (keyWordsTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          keyWordsType_ = java.util.Collections.unmodifiableList(keyWordsType_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.keyWordsType_ = keyWordsType_;
      } else {
        result.keyWordsType_ = keyWordsTypeBuilder_.build();
      }
      if (pieceBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          piece_ = java.util.Collections.unmodifiableList(piece_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.piece_ = piece_;
      } else {
        result.piece_ = pieceBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.databaker.hyzx.speech.StreamingTranscription) {
        return mergeFrom((com.databaker.hyzx.speech.StreamingTranscription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.databaker.hyzx.speech.StreamingTranscription other) {
      if (other == com.databaker.hyzx.speech.StreamingTranscription.getDefaultInstance()) return this;
      if (!other.getTranscribedText().isEmpty()) {
        transcribedText_ = other.transcribedText_;
        onChanged();
      }
      if (keyWordsTypeBuilder_ == null) {
        if (!other.keyWordsType_.isEmpty()) {
          if (keyWordsType_.isEmpty()) {
            keyWordsType_ = other.keyWordsType_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeyWordsTypeIsMutable();
            keyWordsType_.addAll(other.keyWordsType_);
          }
          onChanged();
        }
      } else {
        if (!other.keyWordsType_.isEmpty()) {
          if (keyWordsTypeBuilder_.isEmpty()) {
            keyWordsTypeBuilder_.dispose();
            keyWordsTypeBuilder_ = null;
            keyWordsType_ = other.keyWordsType_;
            bitField0_ = (bitField0_ & ~0x00000002);
            keyWordsTypeBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeyWordsTypeFieldBuilder() : null;
          } else {
            keyWordsTypeBuilder_.addAllMessages(other.keyWordsType_);
          }
        }
      }
      if (pieceBuilder_ == null) {
        if (!other.piece_.isEmpty()) {
          if (piece_.isEmpty()) {
            piece_ = other.piece_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePieceIsMutable();
            piece_.addAll(other.piece_);
          }
          onChanged();
        }
      } else {
        if (!other.piece_.isEmpty()) {
          if (pieceBuilder_.isEmpty()) {
            pieceBuilder_.dispose();
            pieceBuilder_ = null;
            piece_ = other.piece_;
            bitField0_ = (bitField0_ & ~0x00000004);
            pieceBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPieceFieldBuilder() : null;
          } else {
            pieceBuilder_.addAllMessages(other.piece_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.databaker.hyzx.speech.StreamingTranscription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.databaker.hyzx.speech.StreamingTranscription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object transcribedText_ = "";
    /**
     * <pre>
     * 转写结果
     * </pre>
     *
     * <code>string transcribedText = 1;</code>
     */
    public String getTranscribedText() {
      Object ref = transcribedText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transcribedText_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 转写结果
     * </pre>
     *
     * <code>string transcribedText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTranscribedTextBytes() {
      Object ref = transcribedText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transcribedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 转写结果
     * </pre>
     *
     * <code>string transcribedText = 1;</code>
     */
    public Builder setTranscribedText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      transcribedText_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转写结果
     * </pre>
     *
     * <code>string transcribedText = 1;</code>
     */
    public Builder clearTranscribedText() {

      transcribedText_ = getDefaultInstance().getTranscribedText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转写结果
     * </pre>
     *
     * <code>string transcribedText = 1;</code>
     */
    public Builder setTranscribedTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      transcribedText_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.databaker.hyzx.speech.KeyWordsType> keyWordsType_ =
      java.util.Collections.emptyList();
    private void ensureKeyWordsTypeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        keyWordsType_ = new java.util.ArrayList<com.databaker.hyzx.speech.KeyWordsType>(keyWordsType_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.databaker.hyzx.speech.KeyWordsType, com.databaker.hyzx.speech.KeyWordsType.Builder, com.databaker.hyzx.speech.KeyWordsTypeOrBuilder> keyWordsTypeBuilder_;

    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public java.util.List<com.databaker.hyzx.speech.KeyWordsType> getKeyWordsTypeList() {
      if (keyWordsTypeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keyWordsType_);
      } else {
        return keyWordsTypeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public int getKeyWordsTypeCount() {
      if (keyWordsTypeBuilder_ == null) {
        return keyWordsType_.size();
      } else {
        return keyWordsTypeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public com.databaker.hyzx.speech.KeyWordsType getKeyWordsType(int index) {
      if (keyWordsTypeBuilder_ == null) {
        return keyWordsType_.get(index);
      } else {
        return keyWordsTypeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder setKeyWordsType(
        int index, com.databaker.hyzx.speech.KeyWordsType value) {
      if (keyWordsTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.set(index, value);
        onChanged();
      } else {
        keyWordsTypeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder setKeyWordsType(
        int index, com.databaker.hyzx.speech.KeyWordsType.Builder builderForValue) {
      if (keyWordsTypeBuilder_ == null) {
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.set(index, builderForValue.build());
        onChanged();
      } else {
        keyWordsTypeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder addKeyWordsType(com.databaker.hyzx.speech.KeyWordsType value) {
      if (keyWordsTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.add(value);
        onChanged();
      } else {
        keyWordsTypeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder addKeyWordsType(
        int index, com.databaker.hyzx.speech.KeyWordsType value) {
      if (keyWordsTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.add(index, value);
        onChanged();
      } else {
        keyWordsTypeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder addKeyWordsType(
        com.databaker.hyzx.speech.KeyWordsType.Builder builderForValue) {
      if (keyWordsTypeBuilder_ == null) {
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.add(builderForValue.build());
        onChanged();
      } else {
        keyWordsTypeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder addKeyWordsType(
        int index, com.databaker.hyzx.speech.KeyWordsType.Builder builderForValue) {
      if (keyWordsTypeBuilder_ == null) {
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.add(index, builderForValue.build());
        onChanged();
      } else {
        keyWordsTypeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder addAllKeyWordsType(
        Iterable<? extends com.databaker.hyzx.speech.KeyWordsType> values) {
      if (keyWordsTypeBuilder_ == null) {
        ensureKeyWordsTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyWordsType_);
        onChanged();
      } else {
        keyWordsTypeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder clearKeyWordsType() {
      if (keyWordsTypeBuilder_ == null) {
        keyWordsType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        keyWordsTypeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public Builder removeKeyWordsType(int index) {
      if (keyWordsTypeBuilder_ == null) {
        ensureKeyWordsTypeIsMutable();
        keyWordsType_.remove(index);
        onChanged();
      } else {
        keyWordsTypeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public com.databaker.hyzx.speech.KeyWordsType.Builder getKeyWordsTypeBuilder(
        int index) {
      return getKeyWordsTypeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public com.databaker.hyzx.speech.KeyWordsTypeOrBuilder getKeyWordsTypeOrBuilder(
        int index) {
      if (keyWordsTypeBuilder_ == null) {
        return keyWordsType_.get(index);  } else {
        return keyWordsTypeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public java.util.List<? extends com.databaker.hyzx.speech.KeyWordsTypeOrBuilder>
         getKeyWordsTypeOrBuilderList() {
      if (keyWordsTypeBuilder_ != null) {
        return keyWordsTypeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keyWordsType_);
      }
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public com.databaker.hyzx.speech.KeyWordsType.Builder addKeyWordsTypeBuilder() {
      return getKeyWordsTypeFieldBuilder().addBuilder(
          com.databaker.hyzx.speech.KeyWordsType.getDefaultInstance());
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public com.databaker.hyzx.speech.KeyWordsType.Builder addKeyWordsTypeBuilder(
        int index) {
      return getKeyWordsTypeFieldBuilder().addBuilder(
          index, com.databaker.hyzx.speech.KeyWordsType.getDefaultInstance());
    }
    /**
     * <pre>
     * 转写结果中包含热词的内容
     * </pre>
     *
     * <code>repeated .KeyWordsType keyWordsType = 2;</code>
     */
    public java.util.List<com.databaker.hyzx.speech.KeyWordsType.Builder>
         getKeyWordsTypeBuilderList() {
      return getKeyWordsTypeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.databaker.hyzx.speech.KeyWordsType, com.databaker.hyzx.speech.KeyWordsType.Builder, com.databaker.hyzx.speech.KeyWordsTypeOrBuilder>
        getKeyWordsTypeFieldBuilder() {
      if (keyWordsTypeBuilder_ == null) {
        keyWordsTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.databaker.hyzx.speech.KeyWordsType, com.databaker.hyzx.speech.KeyWordsType.Builder, com.databaker.hyzx.speech.KeyWordsTypeOrBuilder>(
                keyWordsType_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        keyWordsType_ = null;
      }
      return keyWordsTypeBuilder_;
    }

    private java.util.List<com.databaker.hyzx.speech.StreamingTranscriptionPiece> piece_ =
      java.util.Collections.emptyList();
    private void ensurePieceIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        piece_ = new java.util.ArrayList<com.databaker.hyzx.speech.StreamingTranscriptionPiece>(piece_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingTranscriptionPiece, com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder, com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder> pieceBuilder_;

    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public java.util.List<com.databaker.hyzx.speech.StreamingTranscriptionPiece> getPieceList() {
      if (pieceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(piece_);
      } else {
        return pieceBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public int getPieceCount() {
      if (pieceBuilder_ == null) {
        return piece_.size();
      } else {
        return pieceBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingTranscriptionPiece getPiece(int index) {
      if (pieceBuilder_ == null) {
        return piece_.get(index);
      } else {
        return pieceBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder setPiece(
        int index, com.databaker.hyzx.speech.StreamingTranscriptionPiece value) {
      if (pieceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePieceIsMutable();
        piece_.set(index, value);
        onChanged();
      } else {
        pieceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder setPiece(
        int index, com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder builderForValue) {
      if (pieceBuilder_ == null) {
        ensurePieceIsMutable();
        piece_.set(index, builderForValue.build());
        onChanged();
      } else {
        pieceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder addPiece(com.databaker.hyzx.speech.StreamingTranscriptionPiece value) {
      if (pieceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePieceIsMutable();
        piece_.add(value);
        onChanged();
      } else {
        pieceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder addPiece(
        int index, com.databaker.hyzx.speech.StreamingTranscriptionPiece value) {
      if (pieceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePieceIsMutable();
        piece_.add(index, value);
        onChanged();
      } else {
        pieceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder addPiece(
        com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder builderForValue) {
      if (pieceBuilder_ == null) {
        ensurePieceIsMutable();
        piece_.add(builderForValue.build());
        onChanged();
      } else {
        pieceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder addPiece(
        int index, com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder builderForValue) {
      if (pieceBuilder_ == null) {
        ensurePieceIsMutable();
        piece_.add(index, builderForValue.build());
        onChanged();
      } else {
        pieceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder addAllPiece(
        Iterable<? extends com.databaker.hyzx.speech.StreamingTranscriptionPiece> values) {
      if (pieceBuilder_ == null) {
        ensurePieceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, piece_);
        onChanged();
      } else {
        pieceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder clearPiece() {
      if (pieceBuilder_ == null) {
        piece_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        pieceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public Builder removePiece(int index) {
      if (pieceBuilder_ == null) {
        ensurePieceIsMutable();
        piece_.remove(index);
        onChanged();
      } else {
        pieceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder getPieceBuilder(
        int index) {
      return getPieceFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder getPieceOrBuilder(
        int index) {
      if (pieceBuilder_ == null) {
        return piece_.get(index);  } else {
        return pieceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public java.util.List<? extends com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder>
         getPieceOrBuilderList() {
      if (pieceBuilder_ != null) {
        return pieceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(piece_);
      }
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder addPieceBuilder() {
      return getPieceFieldBuilder().addBuilder(
          com.databaker.hyzx.speech.StreamingTranscriptionPiece.getDefaultInstance());
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder addPieceBuilder(
        int index) {
      return getPieceFieldBuilder().addBuilder(
          index, com.databaker.hyzx.speech.StreamingTranscriptionPiece.getDefaultInstance());
    }
    /**
     * <pre>
     * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
     * </pre>
     *
     * <code>repeated .StreamingTranscriptionPiece piece = 3;</code>
     */
    public java.util.List<com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder>
         getPieceBuilderList() {
      return getPieceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingTranscriptionPiece, com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder, com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder>
        getPieceFieldBuilder() {
      if (pieceBuilder_ == null) {
        pieceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.databaker.hyzx.speech.StreamingTranscriptionPiece, com.databaker.hyzx.speech.StreamingTranscriptionPiece.Builder, com.databaker.hyzx.speech.StreamingTranscriptionPieceOrBuilder>(
                piece_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        piece_ = null;
      }
      return pieceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamingTranscription)
  }

  // @@protoc_insertion_point(class_scope:StreamingTranscription)
  private static final com.databaker.hyzx.speech.StreamingTranscription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.databaker.hyzx.speech.StreamingTranscription();
  }

  public static com.databaker.hyzx.speech.StreamingTranscription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingTranscription>
      PARSER = new com.google.protobuf.AbstractParser<StreamingTranscription>() {
    public StreamingTranscription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamingTranscription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamingTranscription> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamingTranscription> getParserForType() {
    return PARSER;
  }

  public com.databaker.hyzx.speech.StreamingTranscription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

