// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface StreamingSpeechResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 此识别结果是否为最终结果
   * </pre>
   *
   * <code>bool isFinal = 1;</code>
   */
  boolean getIsFinal();

  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   */
  boolean hasBestTranscription();
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   */
  com.databaker.hyzx.speech.StreamingTranscription getBestTranscription();
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   */
  com.databaker.hyzx.speech.StreamingTranscriptionOrBuilder getBestTranscriptionOrBuilder();
}
