// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface StreamingSpeechRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   */
  boolean hasStreamingSpeechConfig();
  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechConfig getStreamingSpeechConfig();
  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   */
  com.databaker.hyzx.speech.StreamingSpeechConfigOrBuilder getStreamingSpeechConfigOrBuilder();

  /**
   * <pre>
   * 音频数据。每个请求的音频长度最长为60秒。针对实时场景，音频输入的速度超过实时时，性能无法保障，需与依图沟通
   * </pre>
   *
   * <code>bytes audioData = 2;</code>
   */
  com.google.protobuf.ByteString getAudioData();

  public com.databaker.hyzx.speech.StreamingSpeechRequest.RequestPayloadCase getRequestPayloadCase();
}
