// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

/**
 * <pre>
 * 音频流识别请求回应
 * </pre>
 *
 * Protobuf type {@code StreamingSpeechResponse}
 */
public  final class StreamingSpeechResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamingSpeechResponse)
    StreamingSpeechResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingSpeechResponse.newBuilder() to construct.
  private StreamingSpeechResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingSpeechResponse() {
    globalStreamId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamingSpeechResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            globalStreamId_ = s;
            break;
          }
          case 18: {
            com.databaker.hyzx.speech.StreamingSpeechResult.Builder subBuilder = null;
            if (result_ != null) {
              subBuilder = result_.toBuilder();
            }
            result_ = input.readMessage(com.databaker.hyzx.speech.StreamingSpeechResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(result_);
              result_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.databaker.hyzx.speech.StreamingSpeechStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.databaker.hyzx.speech.StreamingSpeechStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.databaker.hyzx.speech.StreamingSpeechResponse.class, com.databaker.hyzx.speech.StreamingSpeechResponse.Builder.class);
  }

  public static final int GLOBALSTREAMID_FIELD_NUMBER = 1;
  private volatile Object globalStreamId_;
  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   */
  public String getGlobalStreamId() {
    Object ref = globalStreamId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      globalStreamId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGlobalStreamIdBytes() {
    Object ref = globalStreamId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      globalStreamId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private com.databaker.hyzx.speech.StreamingSpeechResult result_;
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  public boolean hasResult() {
    return result_ != null;
  }
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  public com.databaker.hyzx.speech.StreamingSpeechResult getResult() {
    return result_ == null ? com.databaker.hyzx.speech.StreamingSpeechResult.getDefaultInstance() : result_;
  }
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  public com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder getResultOrBuilder() {
    return getResult();
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private com.databaker.hyzx.speech.StreamingSpeechStatus status_;
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  public com.databaker.hyzx.speech.StreamingSpeechStatus getStatus() {
    return status_ == null ? com.databaker.hyzx.speech.StreamingSpeechStatus.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  public com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGlobalStreamIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, globalStreamId_);
    }
    if (result_ != null) {
      output.writeMessage(2, getResult());
    }
    if (status_ != null) {
      output.writeMessage(3, getStatus());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGlobalStreamIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, globalStreamId_);
    }
    if (result_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResult());
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.databaker.hyzx.speech.StreamingSpeechResponse)) {
      return super.equals(obj);
    }
    com.databaker.hyzx.speech.StreamingSpeechResponse other = (com.databaker.hyzx.speech.StreamingSpeechResponse) obj;

    boolean result = true;
    result = result && getGlobalStreamId()
        .equals(other.getGlobalStreamId());
    result = result && (hasResult() == other.hasResult());
    if (hasResult()) {
      result = result && getResult()
          .equals(other.getResult());
    }
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result && getStatus()
          .equals(other.getStatus());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GLOBALSTREAMID_FIELD_NUMBER;
    hash = (53 * hash) + getGlobalStreamId().hashCode();
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.StreamingSpeechResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.databaker.hyzx.speech.StreamingSpeechResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 音频流识别请求回应
   * </pre>
   *
   * Protobuf type {@code StreamingSpeechResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamingSpeechResponse)
      com.databaker.hyzx.speech.StreamingSpeechResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.databaker.hyzx.speech.StreamingSpeechResponse.class, com.databaker.hyzx.speech.StreamingSpeechResponse.Builder.class);
    }

    // Construct using com.databaker.hyzx.speech.StreamingSpeechResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      globalStreamId_ = "";

      if (resultBuilder_ == null) {
        result_ = null;
      } else {
        result_ = null;
        resultBuilder_ = null;
      }
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_StreamingSpeechResponse_descriptor;
    }

    public com.databaker.hyzx.speech.StreamingSpeechResponse getDefaultInstanceForType() {
      return com.databaker.hyzx.speech.StreamingSpeechResponse.getDefaultInstance();
    }

    public com.databaker.hyzx.speech.StreamingSpeechResponse build() {
      com.databaker.hyzx.speech.StreamingSpeechResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.databaker.hyzx.speech.StreamingSpeechResponse buildPartial() {
      com.databaker.hyzx.speech.StreamingSpeechResponse result = new com.databaker.hyzx.speech.StreamingSpeechResponse(this);
      result.globalStreamId_ = globalStreamId_;
      if (resultBuilder_ == null) {
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.databaker.hyzx.speech.StreamingSpeechResponse) {
        return mergeFrom((com.databaker.hyzx.speech.StreamingSpeechResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.databaker.hyzx.speech.StreamingSpeechResponse other) {
      if (other == com.databaker.hyzx.speech.StreamingSpeechResponse.getDefaultInstance()) return this;
      if (!other.getGlobalStreamId().isEmpty()) {
        globalStreamId_ = other.globalStreamId_;
        onChanged();
      }
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.databaker.hyzx.speech.StreamingSpeechResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.databaker.hyzx.speech.StreamingSpeechResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object globalStreamId_ = "";
    /**
     * <pre>
     * 此次实时处理的全局唯一ID。
     * </pre>
     *
     * <code>string globalStreamId = 1;</code>
     */
    public String getGlobalStreamId() {
      Object ref = globalStreamId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        globalStreamId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 此次实时处理的全局唯一ID。
     * </pre>
     *
     * <code>string globalStreamId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGlobalStreamIdBytes() {
      Object ref = globalStreamId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        globalStreamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 此次实时处理的全局唯一ID。
     * </pre>
     *
     * <code>string globalStreamId = 1;</code>
     */
    public Builder setGlobalStreamId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      globalStreamId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 此次实时处理的全局唯一ID。
     * </pre>
     *
     * <code>string globalStreamId = 1;</code>
     */
    public Builder clearGlobalStreamId() {

      globalStreamId_ = getDefaultInstance().getGlobalStreamId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 此次实时处理的全局唯一ID。
     * </pre>
     *
     * <code>string globalStreamId = 1;</code>
     */
    public Builder setGlobalStreamIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      globalStreamId_ = value;
      onChanged();
      return this;
    }

    private com.databaker.hyzx.speech.StreamingSpeechResult result_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingSpeechResult, com.databaker.hyzx.speech.StreamingSpeechResult.Builder, com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder> resultBuilder_;
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public boolean hasResult() {
      return resultBuilder_ != null || result_ != null;
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechResult getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.databaker.hyzx.speech.StreamingSpeechResult.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public Builder setResult(com.databaker.hyzx.speech.StreamingSpeechResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public Builder setResult(
        com.databaker.hyzx.speech.StreamingSpeechResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public Builder mergeResult(com.databaker.hyzx.speech.StreamingSpeechResult value) {
      if (resultBuilder_ == null) {
        if (result_ != null) {
          result_ =
            com.databaker.hyzx.speech.StreamingSpeechResult.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        resultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = null;
        onChanged();
      } else {
        result_ = null;
        resultBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechResult.Builder getResultBuilder() {

      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.databaker.hyzx.speech.StreamingSpeechResult.getDefaultInstance() : result_;
      }
    }
    /**
     * <pre>
     * 返回识别结果
     * </pre>
     *
     * <code>.StreamingSpeechResult result = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingSpeechResult, com.databaker.hyzx.speech.StreamingSpeechResult.Builder, com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder>
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.databaker.hyzx.speech.StreamingSpeechResult, com.databaker.hyzx.speech.StreamingSpeechResult.Builder, com.databaker.hyzx.speech.StreamingSpeechResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private com.databaker.hyzx.speech.StreamingSpeechStatus status_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingSpeechStatus, com.databaker.hyzx.speech.StreamingSpeechStatus.Builder, com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.databaker.hyzx.speech.StreamingSpeechStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public Builder setStatus(com.databaker.hyzx.speech.StreamingSpeechStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public Builder setStatus(
        com.databaker.hyzx.speech.StreamingSpeechStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public Builder mergeStatus(com.databaker.hyzx.speech.StreamingSpeechStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.databaker.hyzx.speech.StreamingSpeechStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechStatus.Builder getStatusBuilder() {

      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    public com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.databaker.hyzx.speech.StreamingSpeechStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * 返回识别状态
     * </pre>
     *
     * <code>.StreamingSpeechStatus status = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.databaker.hyzx.speech.StreamingSpeechStatus, com.databaker.hyzx.speech.StreamingSpeechStatus.Builder, com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder>
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.databaker.hyzx.speech.StreamingSpeechStatus, com.databaker.hyzx.speech.StreamingSpeechStatus.Builder, com.databaker.hyzx.speech.StreamingSpeechStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamingSpeechResponse)
  }

  // @@protoc_insertion_point(class_scope:StreamingSpeechResponse)
  private static final com.databaker.hyzx.speech.StreamingSpeechResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.databaker.hyzx.speech.StreamingSpeechResponse();
  }

  public static com.databaker.hyzx.speech.StreamingSpeechResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingSpeechResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamingSpeechResponse>() {
    public StreamingSpeechResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamingSpeechResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamingSpeechResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamingSpeechResponse> getParserForType() {
    return PARSER;
  }

  public com.databaker.hyzx.speech.StreamingSpeechResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

