// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

/**
 * <pre>
 * 指定规则替换文本
 * </pre>
 *
 * Protobuf type {@code WordsReplace}
 */
public  final class WordsReplace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WordsReplace)
    WordsReplaceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WordsReplace.newBuilder() to construct.
  private WordsReplace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WordsReplace() {
    keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WordsReplace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              keywords_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            keywords_.add(s);
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              replace_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            replace_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        keywords_ = keywords_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        replace_ = replace_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_WordsReplace_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.databaker.hyzx.speech.StreamingProtos.internal_static_WordsReplace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.databaker.hyzx.speech.WordsReplace.class, com.databaker.hyzx.speech.WordsReplace.Builder.class);
  }

  public static final int KEYWORDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList keywords_;
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getKeywordsList() {
    return keywords_;
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  public int getKeywordsCount() {
    return keywords_.size();
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  public String getKeywords(int index) {
    return keywords_.get(index);
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKeywordsBytes(int index) {
    return keywords_.getByteString(index);
  }

  public static final int REPLACE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList replace_;
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getReplaceList() {
    return replace_;
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  public int getReplaceCount() {
    return replace_.size();
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  public String getReplace(int index) {
    return replace_.get(index);
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  public com.google.protobuf.ByteString
      getReplaceBytes(int index) {
    return replace_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < keywords_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keywords_.getRaw(i));
    }
    for (int i = 0; i < replace_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, replace_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < keywords_.size(); i++) {
        dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeywordsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < replace_.size(); i++) {
        dataSize += computeStringSizeNoTag(replace_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReplaceList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.databaker.hyzx.speech.WordsReplace)) {
      return super.equals(obj);
    }
    com.databaker.hyzx.speech.WordsReplace other = (com.databaker.hyzx.speech.WordsReplace) obj;

    boolean result = true;
    result = result && getKeywordsList()
        .equals(other.getKeywordsList());
    result = result && getReplaceList()
        .equals(other.getReplaceList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeywordsCount() > 0) {
      hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordsList().hashCode();
    }
    if (getReplaceCount() > 0) {
      hash = (37 * hash) + REPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getReplaceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.databaker.hyzx.speech.WordsReplace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.databaker.hyzx.speech.WordsReplace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * Protobuf type {@code WordsReplace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WordsReplace)
      com.databaker.hyzx.speech.WordsReplaceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_WordsReplace_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_WordsReplace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.databaker.hyzx.speech.WordsReplace.class, com.databaker.hyzx.speech.WordsReplace.Builder.class);
    }

    // Construct using com.databaker.hyzx.speech.WordsReplace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.databaker.hyzx.speech.StreamingProtos.internal_static_WordsReplace_descriptor;
    }

    public com.databaker.hyzx.speech.WordsReplace getDefaultInstanceForType() {
      return com.databaker.hyzx.speech.WordsReplace.getDefaultInstance();
    }

    public com.databaker.hyzx.speech.WordsReplace build() {
      com.databaker.hyzx.speech.WordsReplace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.databaker.hyzx.speech.WordsReplace buildPartial() {
      com.databaker.hyzx.speech.WordsReplace result = new com.databaker.hyzx.speech.WordsReplace(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        keywords_ = keywords_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keywords_ = keywords_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        replace_ = replace_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.replace_ = replace_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.databaker.hyzx.speech.WordsReplace) {
        return mergeFrom((com.databaker.hyzx.speech.WordsReplace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.databaker.hyzx.speech.WordsReplace other) {
      if (other == com.databaker.hyzx.speech.WordsReplace.getDefaultInstance()) return this;
      if (!other.keywords_.isEmpty()) {
        if (keywords_.isEmpty()) {
          keywords_ = other.keywords_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeywordsIsMutable();
          keywords_.addAll(other.keywords_);
        }
        onChanged();
      }
      if (!other.replace_.isEmpty()) {
        if (replace_.isEmpty()) {
          replace_ = other.replace_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureReplaceIsMutable();
          replace_.addAll(other.replace_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.databaker.hyzx.speech.WordsReplace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.databaker.hyzx.speech.WordsReplace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKeywordsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      return keywords_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public Builder setKeywords(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
      keywords_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public Builder addKeywords(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
      keywords_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public Builder addAllKeywords(
        Iterable<String> values) {
      ensureKeywordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keywords_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public Builder clearKeywords() {
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     */
    public Builder addKeywordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKeywordsIsMutable();
      keywords_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReplaceIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        replace_ = new com.google.protobuf.LazyStringArrayList(replace_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReplaceList() {
      return replace_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public int getReplaceCount() {
      return replace_.size();
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public String getReplace(int index) {
      return replace_.get(index);
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReplaceBytes(int index) {
      return replace_.getByteString(index);
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public Builder setReplace(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceIsMutable();
      replace_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public Builder addReplace(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceIsMutable();
      replace_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public Builder addAllReplace(
        Iterable<String> values) {
      ensureReplaceIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, replace_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public Builder clearReplace() {
      replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     */
    public Builder addReplaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReplaceIsMutable();
      replace_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WordsReplace)
  }

  // @@protoc_insertion_point(class_scope:WordsReplace)
  private static final com.databaker.hyzx.speech.WordsReplace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.databaker.hyzx.speech.WordsReplace();
  }

  public static com.databaker.hyzx.speech.WordsReplace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WordsReplace>
      PARSER = new com.google.protobuf.AbstractParser<WordsReplace>() {
    public WordsReplace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WordsReplace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WordsReplace> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WordsReplace> getParserForType() {
    return PARSER;
  }

  public com.databaker.hyzx.speech.WordsReplace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

