// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: real_time_asr.proto

package com.databaker.hyzx.speech;

public interface WordsReplaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WordsReplace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  java.util.List<String>
      getKeywordsList();
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  int getKeywordsCount();
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  String getKeywords(int index);
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  java.util.List<String>
      getReplaceList();
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  int getReplaceCount();
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  String getReplace(int index);
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   */
  com.google.protobuf.ByteString
      getReplaceBytes(int index);
}
